class CfgFontFamilies
{
	class EtelkaNarrowMediumPro
	{
		fonts[]=
		{
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro6",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro7",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro8",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro9",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro10",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro11",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro12",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro13",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro14",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro15",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro16",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro17",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro18",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro19",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro20",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro21",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro22",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro23",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro24",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro25",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro26",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro27",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro28",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro29",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro30",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro31",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro34",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro35",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro37",
			"A3\Uifonts_f\Data\Fonts\EtelkaNarrowMediumPro\EtelkaNarrowMediumPro46"
		};
	};
};