name = "MEOW"
author = "Kotovskiy34"
prefix = "meow"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README*.md",
    "AUTHORS.txt",
    "LICENSE",
    "*.paa",
    "meta.cpp",
]

[version]
git_hash = 0

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
]

[hemtt.launch.rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]